### ISSUE TITLE
Repair Button Update

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#100]
>i thought we agreed that the Repair page will close after a action is pressed, it will stop pressing the button muiltpul times 

>Once a repair is complete you shouldnt be able to open it again from this page 

>i thought we had a page for collected?

>whats the point of having a button for awaiting repair, if it on this page its should already awaiting a repair?

![screenshot 2017-01-13 18 45 43](https://cloud.githubusercontent.com/assets/5702426/23824901/8760ee2c-0677-11e7-8c47-913a59ea7785.png)

![image](https://cloud.githubusercontent.com/assets/5702426/23824960/c3b3c628-0678-11e7-85ae-6ef00c875de0.png)

**Comment by DalvinderSingh** [comment]
Sam,

Also the orders should only go red once its past 24 hours of the quoted time 

I Rather it not show the collected repairs and the BERd repairs on this page because the idea is the empty the pending repair page for the engines (maybe have them under reports)

**Comment by Samyoul** [comment]
>Also the orders should only go red once its past 24 hours of the quoted time

Currently the time remaining text will highlight in red and the row will stay white once there is less than 24 hours until the pickup date.

The order row will also turn red once the pickup date has been exceeded.

Are you asking for the order row to go red once the pickup date has been exceeded by 24 hours?

**Comment by DalvinderSingh** [comment]
No Sorry, you are correct

i forgot what i asked for

**Comment by DalvinderSingh** [comment]
The Parts required feature doesn't work, 

i thought it should pop up with all the parts that i assign to it

**Comment by Samyoul** [comment]
>The Parts required feature doesn't work,
>
>i thought it should pop up with all the parts that i assign to it

On my end it does. Does your user have parts on their account?

**Comment by DalvinderSingh** [comment]
Yes, i have tried it with 3 devices

Try it on my user 
Dilly
6451DSG6451

it should be the iPhone 7 plus pending

**Comment by Samyoul** [comment]
Can you confirm the username and password are correct, the above credentials are failing for me.

**Comment by DalvinderSingh** [comment]
Sorry No caps

6451dsg6451

**Comment by Samyoul** [comment]
It is working for me. Are you sure you are clicking on "Parts Required" ?

![employee repair order notes](https://cloud.githubusercontent.com/assets/5702426/23833281/222a40b6-073b-11e7-8fef-ff85957bb593.png)
![employee repair order notes 1](https://cloud.githubusercontent.com/assets/5702426/23833285/2b539d54-073b-11e7-99f5-28015d223dc2.png)
![employee repair order notes 2](https://cloud.githubusercontent.com/assets/5702426/23833286/2f2c4a84-073b-11e7-9817-56d8b56cf60f.png)

Bare in mind the buttons are in the process of being updated, they will look like : 

![employee repair order notes 3](https://cloud.githubusercontent.com/assets/5702426/23833355/169b856a-073c-11e7-9f11-0a07935854ff.png)

**Comment by DalvinderSingh** [comment]
Sam the parts required button should only be pressed if you don't have that part in stock
Engineer
Checks device and finds he doesn't have that part in stock, he presses that button and the device leaves the awaiting repair page and goes to the awaiting parts page

If the part is in stock you simply just select the part you have used and click repair complete

**Comment by Samyoul** [comment]
> the parts required button should only be pressed if you don't have that part in stock
Engineer
Checks device and finds he doesn't have that part in stock, he presses that button and the device leaves the awaiting repair page and goes to the awaiting parts page
>
>If the part is in stock you simply just select the part you have used and click repair complete

So we need additional functionality? A new "parts used" button which assigns which parts were used in the repair?

**Comment by DalvinderSingh** [comment]
Will that be a long change

**Comment by DalvinderSingh** [comment]
I think the page still should close after an action E,G: Repair complete, Parts Required and BER

**Comment by Samyoul** [comment]
>I think the page still should close after an action E,G: Repair complete, Parts Required and BER

It does on my side.

**Comment by DalvinderSingh** [comment]
Sorry, I will restart my Laptop and check
