### ISSUE TITLE
Cost Margin

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#101]
Sam,

The parts Cost margin is incorrect, 

E.g, if i put the cost at £100 and the Customer price at £200 the margin comes up at £2

**Comment by Samyoul** [comment]
The value is the margin ratio. We are adding the price difference in this issue : https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/80

**Comment by DalvinderSingh** [comment]
Thanks
