### ISSUE TITLE
Book in Page

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#102]
On the book in page all the data goes missing if you forget to enter one of the important fields.

Could the data just stay on the page and highlight where issue is

**Comment by Samyoul** [comment]
This is possible, but it is a little more complex than it may appear, given that this page features a number of dynamically generated input fields.

**Comment by DalvinderSingh** [comment]
i just wouldn't like all the entered number to go if you press enter or process by mistake

**Comment by Samyoul** [comment]
I understand. I'm highlighting that it'll take a little time to complete.
