### ISSUE TITLE
Order Status - Parts Used

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#103]
https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/100#issuecomment-285954073

>Sam the parts required button should only be pressed if you don't have that part in stock
Engineer
Checks device and finds he doesn't have that part in stock, he presses that button and the device leaves the awaiting repair page and goes to the awaiting parts page
>
>If the part is in stock you simply just select the part you have used and click repair complete

Client requires new functionality to record the parts that were used with the order.

**Structure:**

`Orders` belong to many `Parts`
`Parts` belong to many `Orders`

**Comment by Samyoul** [comment]
@DalvinderSingh 
>Will that be a long change

If it is a matter of associating the parts with the order then it would probably take a day.

Do you want the parts that are featured in the "Parts Required" functionality to be automatically included in the list of parts that have been used in the repair?

**Comment by DalvinderSingh** [comment]
Any part I or the customer assigns to that model should display below in that box like a Ajax, we should be able to add multiple parts

**Comment by DalvinderSingh** [comment]
When i say customer i mean the companies buying from me

**Comment by Samyoul** [comment]
Client confirms structure detailed in https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/103#issue-213624702 .

Client confirms `Required Parts` should be considered in this functionality, to be automatically included in the list of parts that have been used in the repair?

**Comment by DalvinderSingh** [comment]
Do you think that the Parts Required and Parts Awaiting Tabs under the Parts Tab could function better under the repair orders Tab, 

If we can order Parts from under that tab i think i could make the page look cleaner (Unsure what i mean, feel free the give me a call)

Not important from 1.0.1 but maybe 1.0
