### ISSUE TITLE
Repair Notes

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#105]
I don't think you should be able to edit the repair Notes in the customers history page, not that important i just would like to add to one of the issues

**Comment by Samyoul** [comment]
Client referring to view `orders/{id}`:

![employee repair order show](https://cloud.githubusercontent.com/assets/5702426/23836352/a74cd1c2-076e-11e7-96d1-eaaa3f6bf8ca.png)
