### ISSUE TITLE
Sign Up Issue 

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#107]
Sam, 

This comes up if you try and Sign up, i understand they need to confirm the email but i think it should just come up saying that not big cross in your face

![image](https://cloud.githubusercontent.com/assets/26223016/23878891/de51d540-0841-11e7-9c9c-e4389cf25c33.png)

**Comment by DalvinderSingh** [comment]
This issue is still happening

**Comment by Samyoul** [comment]
This issue will still happen until it has been resolved. Resolved issues are marked as closed, this issue is currently open
