### ISSUE TITLE
The Pricing 

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#109]
@Samyoul the pricing is wrong, it says 24.99 including tax not excluding Tax

**Comment by Samyoul** [comment]
Where does it say this?

**Comment by DalvinderSingh** [comment]
when you try and pay and subscribe 

Also, it dont let me pay. it just loads for ages once I've entered my details in

**Comment by DalvinderSingh** [comment]
Could you try and pay please and i will just send you the money

**Comment by Samyoul** [comment]
24.99 + VAT
