### ISSUE TITLE
Make chart colours lighter

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#114]
![700c9264-6939-45b2-a142-be2ec56dd821](https://cloud.githubusercontent.com/assets/5702426/24121413/18b544c4-0db0-11e7-8b16-1c30d2a2b792.jpeg)

Perhaps use more pastel versions of the same colour.

**Comment by Samyoul** [comment]
@DalvinderSingh how do you feel about these colours?

![dashboard](https://cloud.githubusercontent.com/assets/5702426/24122652/7e3483b0-0db4-11e7-882a-1a11b20fe85e.png)

**Comment by DalvinderSingh** [comment]
Thats much better
