### ISSUE TITLE
When Order's status is changed

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#136]
Notify user where the order can now be found.

**Comment by formaldehid** [comment]
Can you give me example of notification?

**Comment by Samyoul** [comment]
I think that using Bootstrap Alerts will be enough. http://getbootstrap.com/components/#alerts

Placing the alert at the top of the content div.

So if a user updates the status of an order from "Awaiting Repair" to "BER" the application will show to the user.

"**Update!** Order {{`order_id`}} can now be found in the BER list, click here to see the list {{`BER_link`}}"
