### ISSUE TITLE
Email reset

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#140]
Once you have added your email address in, it should provide you with a link/call to action button to log into
again. Perhaps saying ‘Try logging in again’. There isn’t even a home button to press. How does one go back?
Instead on this page one may enter the email address in again, therefore it will ping them another email reset
link.
When resetting the password, you may use your phone, it then logs in via that device. I may want to log in
again on PC so I need to know how to get back on the PC.

![image](https://user-images.githubusercontent.com/26223016/27938145-fe86a472-62b3-11e7-8c63-969d2e42dddb.png)

**Comment by Samyoul** [comment]
Ok, so after the user sends the password reset email you would like the application to redirect the user to the home page with a success message informing the user that they should receive an email with instructions to reset their password.

Is this correct?

**Comment by Samyoul** [comment]
@DalvinderSingh Just to check, was my last message was correct?

**Comment by DalvinderSingh** [comment]
Yes thats right



-- 
Regards,

Dalvinder Singh Ghuman
Director
Diltek LTD
