### ISSUE TITLE
Questions Tab

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#141]
At the moment the suggestion tab is at the top, perhaps now
as we are in early stages we should promote this a little more.
It says you can hide this message. 

Perhaps adding a small pop up window at the bottom right
hand side. Easy accessible and perhaps we have a small link
to say hide and it hides away on the side so users will always
know it's there on every page. Also ‘Found a bug’? Do you
want to use this? Shows your site probably has bugs and
having issues, Negative phrase.

![image](https://user-images.githubusercontent.com/26223016/27938184-42a0f0d6-62b4-11e7-9b68-44e0584bea2a.png)

![image](https://user-images.githubusercontent.com/26223016/27938188-4894cf8a-62b4-11e7-889c-ece95d45190e.png)

**Comment by Samyoul** [comment]
We could add a little bug icon into the orange box. Like this http://fontawesome.io/icon/bug/

![fa bug font awesome icons 1](https://user-images.githubusercontent.com/5702426/28164933-8bcfa8aa-67c9-11e7-9393-aa608bcb1a9a.png)
