### ISSUE TITLE
Summary Page

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#146]
I like this, how hard is it to get this info

![image](https://user-images.githubusercontent.com/26223016/27938368-8d1e81e0-62b5-11e7-9ce3-b85b012e5a4a.png)

**Comment by Samyoul** [comment]
It isn't difficult to get this information.

I presume the following:

**Open Tickets** : Repairs currently not completed
**My Tickets** : Repairs currently not completed assigned to me / created by me
**My Upcoming Appointments** : Repairs assigned to me with collections in the next 3 days?
**New Tickets Added** : Number of repairs added in the last 30 days
**Customers Added** : Number of customers added in the last 30 days

**Gross Sales** : Total value of quotes for repairs completed in the last 30 days
**Net Sales** : Total value of quotes for repairs completed in the last 30 days - VAT

Are my presumptions correct?

**Comment by DalvinderSingh** [comment]
Yes that seems fine, But i think it should show total repairs as i dont think we have the features to assign repairs to a employee

**Comment by Samyoul** [comment]
>I tried to analyze DB, but could not manage to understand data flow. what is ticket, and how to see if it has been completed. Also how to calculate sales figures.

- Ticket are represented by the `Order` model.
- The `quote` field represents that sales value of an Order.
- The `status_id` field represents the completion status of an Order.
- The different statuses are maintained in `Status` Enum model

**Comment by Samyoul** [comment]
Have summary page show in orange.

**Comment by Samyoul** [comment]
We need to also have this data on the dashboard. See issue #143 for more details
