### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by DalvinderSingh** [Samyoul/The-ultimate-repair-system-issues#148]
Can these be removed please as they dont work

![image](https://user-images.githubusercontent.com/26223016/27938508-4ed6cdd8-62b6-11e7-8aad-2120a209984e.png)

**Comment by Samyoul** [comment]
@DalvinderSingh Do you have any social media accounts for Turs? We can add them if you do. Otherwise it isn't a problem to remove these links.

**Comment by DalvinderSingh** [comment]
At the moment we dont have any
