### ISSUE TITLE
Parts

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#21]
_From @jcergolj on November 9, 2016 17:31_

I saw `Parts` option on top navbar. Is this something that needs to be implemented?

_Copied from original issue: Samyoul/The-ultimate-repair-system#19_

**Comment by Samyoul** [comment]
![screenshot 2017-01-13 18 44 25](https://cloud.githubusercontent.com/assets/5702426/22297006/e1b78ebc-e313-11e6-864c-0d96cceed5ae.png)
![screenshot 2017-01-13 18 45 43](https://cloud.githubusercontent.com/assets/5702426/22297023/f52c71b0-e313-11e6-86cc-5326a55d9df3.png)
![screenshot 2017-01-13 18 46 12](https://cloud.githubusercontent.com/assets/5702426/22297034/01828396-e314-11e6-8109-ed3864d47983.png)
![screenshot 2017-01-13 18 46 07](https://cloud.githubusercontent.com/assets/5702426/22297029/f9e6ee7e-e313-11e6-8355-6750256a1c0a.png)
![screenshot 2017-01-13 18 46 36](https://cloud.githubusercontent.com/assets/5702426/22297060/164ae0d4-e314-11e6-8e36-ac37a5396418.png)
![screenshot 2017-01-13 18 48 52](https://cloud.githubusercontent.com/assets/5702426/22297090/28af893c-e314-11e6-9dc5-b5909ec15bd6.png)
![screenshot 2017-01-13 18 49 04](https://cloud.githubusercontent.com/assets/5702426/22297089/28ae199e-e314-11e6-8719-864c4d46a03d.png)
![screenshot 2017-01-13 18 52 01](https://cloud.githubusercontent.com/assets/5702426/22297129/403c097c-e314-11e6-93cb-8c396d238e62.png)
![screenshot 2017-01-13 18 57 32](https://cloud.githubusercontent.com/assets/5702426/22297150/58963362-e314-11e6-840c-dd1734784d02.png)
![screenshot 2017-01-13 18 58 21](https://cloud.githubusercontent.com/assets/5702426/22297151/5898c97e-e314-11e6-845a-608f5c9ca336.png)
![screenshot 2017-01-13 18 58 56](https://cloud.githubusercontent.com/assets/5702426/22297152/589eb5dc-e314-11e6-93c2-003fd078d080.png)
![screenshot 2017-01-13 19 03 54](https://cloud.githubusercontent.com/assets/5702426/22297185/753c87f0-e314-11e6-8195-364673840b72.png)
![screenshot 2017-01-13 19 04 34](https://cloud.githubusercontent.com/assets/5702426/22297186/753f480a-e314-11e6-924b-9e6f6ae687ae.png)
![screenshot 2017-01-13 19 04 59](https://cloud.githubusercontent.com/assets/5702426/22297187/75438ce4-e314-11e6-8842-0b659f01309f.png)

**Comment by jcergolj** [comment]
Who can add/edit/delete parts? Only admin or employees too?
How are `parts type` created?
`In addition to this the application will add a note detailing the parts that were required along with the datetime.` - what si datetime?

**Comment by Samyoul** [comment]
>Who can add/edit/delete parts? Only admin or employees too?

Only subscriber Admin

>How are `parts type` created?

Via a `parts type` CRUD

>`In addition to this the application will add a note detailing the parts that were required along with the datetime.` - what si datetime?

Datetime, is data that represents date and time ( http://www.php.net/manual/en/class.datetime.php ). Eg `2011-01-01T15:03:01`

**Comment by jcergolj** [comment]
Sorry for the wrong question. What datetime should be stored?

**Comment by Samyoul** [comment]
>Sorry for the wrong question. What datetime should be stored?

Ah, no problem, I thought it was a weird question for someone as proficient as you. The current datetime. Although notes record the datetime they were created at any way so this would happen automatically.

**Comment by jcergolj** [comment]
What fields does `platform type` has? Id, Name, created_at, updated_at? Anything else?

**Comment by Samyoul** [comment]
No, Nothing else, your design is fine.

**Comment by jcergolj** [comment]
Where should `Parts Required Screen` and `Parts Awaiting Screen` be placed? Can you send me image with example?

**Comment by Samyoul** [comment]
![owner faults](https://cloud.githubusercontent.com/assets/5702426/22881355/fa418e5a-f1dd-11e6-9b49-2edb5cff676f.png)

**Comment by jcergolj** [comment]
Thanks.

**Comment by jcergolj** [comment]
I am done for now with parts. Let me know if I've missed something and/or what improvements should I make. You must run migration and re-run StatusTableSeeder.

**Comment by Samyoul** [comment]
How do you require parts on an order?

Clicking "Awaiting Parts" only changes the status

![employee repair order notes](https://cloud.githubusercontent.com/assets/5702426/22908274/6f8edc96-f245-11e6-96bd-57c92b1bd189.png)

**Comment by Samyoul** [comment]
Ignore that last message. I see the problem.

**Comment by jcergolj** [comment]
Ok. I raised invoice on PPH.
