### ISSUE TITLE
Remove source code and branches From This Repo

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#25]
Could you reset this repo back to its original state?

**Comment by Samyoul** [comment]
This code is still accessible via the commit https://github.com/Samyoul/The-ultimate-repair-system-issues/commit/eeb5fa38a7add23bc2

**Comment by jcergolj** [comment]
The easiest way would be to create a new branch and set it to default. Then delete master. And create a new branch called master. But I don't have access right to do so.

https://help.github.com/articles/setting-the-default-branch/

**Comment by Samyoul** [comment]
Resolved.
