### ISSUE TITLE
Order Create - Inline Fault Allocation

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#32]
The current method of allocating a fault to a device needs to be simplified for handling devices with multiple faults. We require faults to assigned to a device the same way people are tagged in a facebook comment.

Please see functionality shown in Select 2 Tagging https://select2.github.io/examples.html#tags

This functionality needs to be given on Job creation in the order create view.

All faults selected will share the same warranty status for the purpose of creating Jobs.

![employee new repair order](https://cloud.githubusercontent.com/assets/5702426/21909711/00b0c02a-d911-11e6-88e0-66ea2b6a92cf.png)

Following the completion of this issue, issue https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/34 would be a logical next step.

**Comment by jcergolj** [comment]
So here I should replace dropdown with tags where tags are faults?

**Comment by Samyoul** [comment]
>So here I should replace dropdown with tags where tags are faults?

Yes, this is correct.
