### ISSUE TITLE
Order Create - Customer Creation Alert

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#33]
When creating a new customer via the customer creation page I get the following alert message:

![screenshot 2017-01-12 21 07 46](https://cloud.githubusercontent.com/assets/5702426/21908800/3e01e2d2-d90d-11e6-9a1c-6e9b7cb36e60.png)

The customer is created, and the application does not suffer any other unexpected behaviour.

**Comment by jcergolj** [comment]
I was trying to fix this, but looks like this error is randomly showing up. This has something to do with javascript tables that I had to move from .html files you send me. Maybe the guy who made .html files knows more about this error.

**Comment by Samyoul** [comment]
Ok, I'll highlight this issue to the html guys
