### ISSUE TITLE
Order Create - Device Create - Add Faults Tags

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#34]
Once issue https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/32 and issue https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/6 have been resolved the workflow of the order creation needs to be streamlined further by adding the Fault tags during the device creation stage. See below. 

![employee new repair order](https://cloud.githubusercontent.com/assets/5702426/21909276/2542325e-d90f-11e6-91ca-8d5cac017788.png)

**Comment by jcergolj** [comment]
I am not sure if this makes sense. Shouldn't faults be assigned to jobs rather than devices? A device could be damaged multiple times and not at the same time. Assigning faults here would mean that device has all the faults even some of them were resolved in the past. Do I miss something?

**Comment by Samyoul** [comment]
Yes, Faults are assigned to jobs you are correct.

But during the Order Create process the user wants to be able to do as much as possible without having to go to additional screens to perform other things.

Adding a faults sections to the device creation screen allows the user to both create and assign a device and assign faults to the job in a single action. This feature of added faults during the device creation screen is only for the Order Create page.

**Comment by jcergolj** [comment]
So only when a new device is created an option to show faults is enabled? If you are editing device this is not possible? Also, should warranty checkbox be displayed too?

**Comment by Samyoul** [comment]
>So only when a new device is created an option to show faults is enabled?

Yes, this is correct, only when on the Order Create page.

>If you are editing device this is not possible?

Correct.

>Also, should warranty checkbox be displayed too?

Yes, only when on the Order Create page.
