### ISSUE TITLE
Statics Dashboard, 

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#5]
_From @Samyoul on December 20, 2016 18:35_

for repairs, number of jobs waiting for repairs, parts, collection, past quoted time

_Copied from original issue: Samyoul/The-ultimate-repair-system#62_

**Comment by Samyoul** [comment]
The statistics page needs to be the default page that the subscriber is directed to after they log in.

The following order statistics are required to be shown:

* Percent of Repairs Used - Pie Chart (Repairs used in period vs repairs remaining in period)
* Repair Statuses - Horizontal Bar Graph - number of jobs waiting for:
    * repairs
    * parts
    * collection
    * not repaired and past quoted time

**Comment by jcergolj** [comment]
My quote would be 130GBP

**Comment by jcergolj** [comment]
* repairs - status_id 1
    * parts - status_id 3
    * collection - status_id 2
    * not repaired and past quoted time - status_id ???

**Comment by Samyoul** [comment]
> What is BER status?

See https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/47 this gives details of what BER is.
