### ISSUE TITLE
Device Creation - Input with AJAX auto suggest

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#6]
_From @Samyoul on December 20, 2016 18:30_

Following on from issue https://github.com/Samyoul/The-ultimate-repair-system/issues/45 , we need an AJAX suggest search input in the place of the select inputs.

This will replace the current select boxes, and will show only a single input field which will show both make and model, but will make AJAX calls to allow the user to select the model they wish to create a device of.

![employee new repair order](https://cloud.githubusercontent.com/assets/5702426/21362903/27c69b12-c6e2-11e6-9046-30446fb783ba.png)

_Copied from original issue: Samyoul/The-ultimate-repair-system#61_

**Comment by jcergolj** [comment]
So similar functionality as omnium search? So autocomplete with ability to search for models?

**Comment by Samyoul** [comment]
Yes. In the option text we need to show both the `Make` name and the `Model` name so that the user is certain they are assigning the correct model to the device. As there may be models with the same name but belong to different makes.

**Comment by jcergolj** [comment]
OK.
