### ISSUE TITLE
Additional Pie chart showing Orders by status

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#60]
Remove repairs used pie chart when there is unlimited repairs on the subscription.

**Comment by DalvinderSingh** [comment]
I still like the idea of a Pie chart, just have it showing all the pending repairs

**Comment by Samyoul** [comment]
>I still like the idea of a Pie chart, just have it showing all the pending repairs

That is what this issue describes.

**Comment by DalvinderSingh** [comment]
Okay, its just currently we have no Pie Chart

Also is it possible to make them lighter colours as we discussed before

**Comment by formaldehid** [comment]
I'm not sure what I have to do with this issue. I would be grateful if you provide me screen and more explanation where and in which cases I remove/add pie chart. Thank you

**Comment by Samyoul** [comment]
Currently if the user has a subscription that has a limit on the number of orders the user can create the dashboard looks like this:

![dashboard](https://cloud.githubusercontent.com/assets/5702426/24122652/7e3483b0-0db4-11e7-882a-1a11b20fe85e.png)

Currently the logic check is : https://github.com/Samyoul/The-ultimate-repair-system/blob/master/app/Http/Controllers/DashboardController.php#L18 . Ideally the logic should check if the plan has a limit on order creation rather than what the plan's name is. If the plan is unlimited the above **pie chart** should not show.

---

Additionally, we need a 2nd pie chart that can be shown regardless of what plan limitation the subscriber has. This chart should show the number of each order by status, excluding `BER` and `Collected`.

**Comment by Samyoul** [comment]
Resolved with https://github.com/Samyoul/The-ultimate-repair-system/pull/93
