### ISSUE TITLE
Test Subscription

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#69]
Subscribe and pay

**Comment by DalvinderSingh** [comment]
sorry, i didnt mean to close

**Comment by DalvinderSingh** [comment]
do you need me to pay to test this

**Comment by Samyoul** [comment]
Test completed, payment processed successfully.

**Comment by Samyoul** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/5702426/24582590/0b374606-172b-11e7-9432-64b252c940b8.png)
