### ISSUE TITLE
CMS functionality for public pages.

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#8]
_From @Samyoul on December 20, 2016 18:22_

_Copied from original issue: Samyoul/The-ultimate-repair-system#59_

**Comment by Samyoul** [comment]
Functionality:

Only to be able to change the text on the home page. No functionality to create pages.

**Comment by jcergolj** [comment]
We need to define which text can be changed on homepage.

**Comment by Samyoul** [comment]
Please see the below image:

![home](https://cloud.githubusercontent.com/assets/5702426/21983945/88ebd8d0-dbeb-11e6-87ce-d8e9d604e5d0.png)

NOTE: The Features Block should allow the user the ability to add or remove features.

**Comment by jcergolj** [comment]
I'll be working on this tomorrow. Is there any suggestion how I should do this. Multiple forms on a single page. Each text edit option on its own page...?

**Comment by Samyoul** [comment]
I think that a page with multiple forms would be the best approach.

**Comment by jcergolj** [comment]
What I am thinking is to remove delete and create a new block and just leave Edit button for each of the created blocks. What do you think? I am thinking also of adding reset link to each block that would reset html to default? For extra 30 GBP?
![screenshot from 2017-01-30 20-17-34](https://cloud.githubusercontent.com/assets/6940394/22437783/a891d056-e729-11e6-84b8-263e55b16fb4.png)

**Comment by jcergolj** [comment]
run inside terminal

php artisan db:seed --class=HomepageFeaturesTableSeeder

php artisan db:seed --class=HomepageContentsTableSeeder

**Comment by Samyoul** [comment]
Why do you put files into application storage to be accessed from the frontend?

**Comment by Samyoul** [comment]
Ah I see. Because this will allow admin to upload files.

Don't we need functionality of transfer from application storage to the publicly accessible domain?

**Comment by Samyoul** [comment]
Icons do not show on `/admins/features`

![admins homepage features](https://cloud.githubusercontent.com/assets/5702426/22469468/0980b036-e7c4-11e6-9a9c-c2f47a9e165e.png)

**Comment by Samyoul** [comment]
There is also a minor bug:

https://github.com/Samyoul/The-ultimate-repair-system/commit/e1676c44705d036bf309b098947264b26081cbe2#diff-3bb220ccc4f81a6f4771f31b03942155R48

```HTML
<img style="width:117px;height117px;" src="{{ $feature->icon_url }}" alt="">
```

Should be

```HTML
<img style="width:117px;height:117px;" src="{{ $feature->icon_url }}" alt="">
```

**Comment by jcergolj** [comment]
Can you send me url of missing img?
Is storage/img folder empty?

**Comment by jcergolj** [comment]
`Don't we need functionality of transfer from application storage to the publicly accessible domain?`
php artisan storage:link

`Ah I see. Because this will allow admin to upload files.`

yes

**Comment by Samyoul** [comment]
I've created the symbolic link between the app storage and public storage and the missing icons were resolved.

I will create a separate issue for the styling bugs.
