### ISSUE TITLE
Parts List

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#80]
Add VAT option to be added to the quote costs `50 (Ex VAT 40.00)`
Show the margin as well as price difference.

![screenshot 2017-01-13 18 44 25](https://cloud.githubusercontent.com/assets/5702426/23069974/4f8d1942-f521-11e6-94c4-4aa7a066e0f7.png)

**Comment by DalvinderSingh** [comment]
The margin is still wrong

**Comment by Samyoul** [comment]
As mentioned in https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/101#issuecomment-285955496 The value is the margin ratio.

This issue has not been marked as closed and so will still not be resolved.

**Comment by Samyoul** [comment]
Resolved https://github.com/Samyoul/The-ultimate-repair-system/pull/81
