### ISSUE TITLE
Order Create - Employee Pin

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#83]
Change "Pin" to "Employee Pin".

If the team has more than 1 user make pin mandatory.

**Comment by DalvinderSingh** [comment]
Can this change be done before i send it out please

**Comment by Samyoul** [comment]
This has been done in with https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/91 .

There's only the trivial `Change "Pin" to "Employee Pin".` part left
