### ISSUE TITLE
Status Update Button Sometimes has Error

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#90]
>All the buttons come up with this error

![image 2](https://cloud.githubusercontent.com/assets/5702426/23411284/c23a9d7e-fdc9-11e6-8945-90bfc257065b.png)

Nothing appears in the error logs ...

**Comment by Samyoul** [comment]
@DalvinderSingh I am unable to reproduce this issue. Can you give some details?

- What is the url on which you experience the problem?
- What is the current status of the order?

**Comment by DalvinderSingh** [comment]
The order is awaiting repair but none of the buttons work

**Comment by Samyoul** [comment]
>What is the url on which you experience the problem?

Could you supply the url you have this problem on?

**Comment by DalvinderSingh** [comment]
http://turs.co.uk/notes?order_id=13

**Comment by Samyoul** [comment]
Does this problem happen on any other orders?

**Comment by DalvinderSingh** [comment]
Yes all

**Comment by DalvinderSingh** [comment]
even when i book a new device in

**Comment by Samyoul** [comment]
Ah, I think this may be a JS update issue.

Could you press on your keyboard `Ctrl + F5`, then try again.

**Comment by DalvinderSingh** [comment]
No, its still happening
User name : dilly
Password : 6451dsg6451

**Comment by Samyoul** [comment]
Hmmm, very odd. Using the above credentials I was able to change the status multiple times.

**Comment by Samyoul** [comment]
What is the browser and operating system you are using?

**Comment by DalvinderSingh** [comment]
Windows 7 and Chrome

**Comment by DalvinderSingh** [comment]
This issue happens with all the PCs at work, its due to our security. could this also happen with a customer using the site

If so could error state that the issue is due the systems they are using

**Comment by Samyoul** [comment]
>This issue happens with all the PCs at work, its due to our security. could this also happen with a customer using the site
>
>If so could error state that the issue is due the systems they are using

Only if we can detect it. What is your work's security doing to cause these errors? Do you know?

**Comment by Samyoul** [comment]
And can I confirm that for this issue and issue https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/94 that you were successfully able to test on your home computers?

**Comment by DalvinderSingh** [comment]
I have no idea, i didnt get time to do it on the computer but i tried it on my phone and it worked

Could it have anything to do with Java

**Comment by Samyoul** [comment]
>Could it have anything to do with Java

No. This application doesn't use Java.

Who told you or how did you know the error was due to your work's security?

**Comment by DalvinderSingh** [comment]
We have a few restrictions sometimes due to the security, i was just thinking this could be one of them

**Comment by Samyoul** [comment]
Merged into https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/99
