### ISSUE TITLE
The update function doesn't work

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#94]
>The update function doesn't work, i have also tried it on the update parts page

![image](https://cloud.githubusercontent.com/assets/5702426/23608928/88f79fa0-0263-11e7-8220-4892e3a5ba52.png)

**Comment by Samyoul** [comment]
@DalvinderSingh What happens when you press update? Are you logged in as a subscriber or as a super admin?

**Comment by DalvinderSingh** [comment]
Super Admin



-- 
Regards,

Dalvinder Singh Ghuman
Director
Diltek LTD

**Comment by Samyoul** [comment]
@DalvinderSingh and what happens when you press update?

**Comment by DalvinderSingh** [comment]
nothing, its doesn't move from that page

**Comment by Samyoul** [comment]
This may be a JS update issue.

Could you press on your keyboard `Ctrl + F5`, then try again.

**Comment by DalvinderSingh** [comment]
still doesn't work

**Comment by Samyoul** [comment]
Strange. I used the credential you supplied here : https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/90#issuecomment-284409583 and was able to update without any issue.

**Comment by DalvinderSingh** [comment]
It doesn't update on Super admin for that issue

**Comment by Samyoul** [comment]
With my super admin credentials I am able to update without any issues.

**Comment by DalvinderSingh** [comment]
i will check on a different PC at home

**Comment by Samyoul** [comment]
If you could that would be great. I've tested this issue and https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/90 on multiple machines and I haven't been able to replicate either of these issues.

**Comment by Samyoul** [comment]
https://github.com/Samyoul/The-ultimate-repair-system-issues/issues/99
