### ISSUE TITLE
Admin Parts Creation - Model always shows as 'url'

### ISSUE THREAD

**Issue by Samyoul** [Samyoul/The-ultimate-repair-system-issues#97]
>Every model comes up as url if you are trying to add parts

![image](https://cloud.githubusercontent.com/assets/5702426/23609389/add46a4a-0265-11e7-8c81-7e56fe7bb0b4.png)

**NOTE:**
This functionality works correctly on subscriber Parts creation

**Comment by DalvinderSingh** [comment]
The error comes up on the super admin page

**Comment by Samyoul** [comment]
No need to give feed back on this. It is marked "awaiting merge"
